### ISSUE TITLE
tagging does not work

### ISSUE THREAD

**Issue by vhkyang** [browneyedsoul/remnote-plugins#25]
Sorry to bother you, but I can't seem to get the plugin to work. I've tried multiple times to follow the instructions and tag the plugin, but it never seems to work. Could you help me out?
![Screenshot (12)](https://github.com/browneyedsoul/RemNote-RemTree/assets/152047680/58cba5e1-ea1b-4a64-a677-de8eafad200a)

Thanks.

**Comment by browneyedsoul** [comment]
The slash is only for opening the Slash command dialog. This plugin doesn't require you to manually tag a rem. You can simply summon this message in your workspace.
![smA7n5Ed-D2byoe6y-HQsZ5k8u-hmdlcd5Z-2YpncWtW](https://github.com/browneyedsoul/remnote-plugins/assets/56161102/d5352f7f-8618-4907-9136-d2b447e88f33)
