### ISSUE TITLE
Improve How to Use

### ISSUE THREAD

**Issue by bjsi** [browneyedsoul/remnote-plugins#58]
- Could you add a picture which shows how to add icons without using the tables plugin? Otherwise people will get confused if they don't have the tables plugin installed :)

![image](https://user-images.githubusercontent.com/58147075/215430919-16d8baed-48df-4eab-9e5e-af61e6b4fd76.png)

**Comment by browneyedsoul** [comment]
https://feedback.remnote.com/p/upload-custom-icons-for-documents
